version: "3.4"
services:
  spring-boot-consul:
    build: ./spring-boot-consul
    container_name: 'spring-boot-consul'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8081:8081
    networks:
      - consul-network